version: 1.0.{build}

branches:
  only:
    - master

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

configuration: Debug

build:
  project: DotNetProjects.WPF.Converters\DotNetProjects.WPF.Converters.sln

after_build:
  - ps: .\nuget\pack.ps1
  
artifacts:
  - path: DotNetProjects.WPF.Converters\DotNetProjects.WPF.Converters\bin\Debug\DotNetProjects.WPF.Converters.dll
    name: DotNetProjects.WPF.Converters.dll
  - path: DotNetProjects.WPF.Converters\DotNetProjects.WPF.Converters\bin\Debug\DotNetProjects.WPF.Converters.pdb
    name: DotNetProjects.WPF.Converters.pdb
  - path: '**\DotNetProjects*.nupkg'

#uncomment to publish to NuGet
deploy:
  provider: NuGet
  api_key:
    secure: bdhemLvYgto+o1hjkJ9OhVRANxW6+U9RTGQre/KqyV3mFWmN5BQA6ZpMoHbjsaJW
  artifact: /.*\.nupkg/
  
  
  
